global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8080"]

  - job_name: "ai-triage"
    static_configs:
      - targets: ["ai-triage:9101"]

  - job_name: "blockchain-service"
    static_configs:
      - targets: ["blockchain-service:9100"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
